when@dev:
    debug:
        # Forwards VarDumper Data clones to package.json centralized server allowing to inspect dumps on CLI or in your browser.
        # See the "server:dump" command to start package.json new server.
        dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
